// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package contentsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeContent = `-- name: CompleteContent :one
UPDATE content
SET
    upload_status = 'uploaded',
    effective_mime_type = $1,
    gcs_uri = $2,
    public_url = $3,
    object_generation = $4,
    size_bytes = $5,
    completed_at = $6,
    updated_at = $7
WHERE bucket = $8 AND object_name = $9
  AND (object_generation IS NULL OR object_generation <= $4::bigint)
RETURNING id, user_id, parent_id, project_id, declared_mime_type, effective_mime_type, bucket, object_name, gcs_uri, public_url, upload_status, object_generation, size_bytes, completed_at, created_at, updated_at
`

type CompleteContentParams struct {
	EffectiveMimeType *string
	GcsUri            *string
	PublicUrl         *string
	ObjectGeneration  *int64
	SizeBytes         *int64
	CompletedAt       pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Bucket            string
	ObjectName        string
}

func (q *Queries) CompleteContent(ctx context.Context, arg CompleteContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, completeContent,
		arg.EffectiveMimeType,
		arg.GcsUri,
		arg.PublicUrl,
		arg.ObjectGeneration,
		arg.SizeBytes,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.Bucket,
		arg.ObjectName,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.ProjectID,
		&i.DeclaredMimeType,
		&i.EffectiveMimeType,
		&i.Bucket,
		&i.ObjectName,
		&i.GcsUri,
		&i.PublicUrl,
		&i.UploadStatus,
		&i.ObjectGeneration,
		&i.SizeBytes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContent = `-- name: CreateContent :one
INSERT INTO content (
    id,
    user_id,
    parent_id,
    project_id,
    declared_mime_type,
    bucket,
    object_name,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) RETURNING id, user_id, parent_id, project_id, declared_mime_type, effective_mime_type, bucket, object_name, gcs_uri, public_url, upload_status, object_generation, size_bytes, completed_at, created_at, updated_at
`

type CreateContentParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ParentID         pgtype.UUID
	ProjectID        pgtype.UUID
	DeclaredMimeType string
	Bucket           string
	ObjectName       string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.ProjectID,
		arg.DeclaredMimeType,
		arg.Bucket,
		arg.ObjectName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.ProjectID,
		&i.DeclaredMimeType,
		&i.EffectiveMimeType,
		&i.Bucket,
		&i.ObjectName,
		&i.GcsUri,
		&i.PublicUrl,
		&i.UploadStatus,
		&i.ObjectGeneration,
		&i.SizeBytes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentByBucketAndName = `-- name: GetContentByBucketAndName :one
SELECT id, user_id, parent_id, project_id, declared_mime_type, effective_mime_type, bucket, object_name, gcs_uri, public_url, upload_status, object_generation, size_bytes, completed_at, created_at, updated_at FROM content
WHERE bucket = $1 AND object_name = $2
`

type GetContentByBucketAndNameParams struct {
	Bucket     string
	ObjectName string
}

func (q *Queries) GetContentByBucketAndName(ctx context.Context, arg GetContentByBucketAndNameParams) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByBucketAndName, arg.Bucket, arg.ObjectName)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.ProjectID,
		&i.DeclaredMimeType,
		&i.EffectiveMimeType,
		&i.Bucket,
		&i.ObjectName,
		&i.GcsUri,
		&i.PublicUrl,
		&i.UploadStatus,
		&i.ObjectGeneration,
		&i.SizeBytes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentByIDAndUser = `-- name: GetContentByIDAndUser :one
SELECT id, user_id, parent_id, project_id, declared_mime_type, effective_mime_type, bucket, object_name, gcs_uri, public_url, upload_status, object_generation, size_bytes, completed_at, created_at, updated_at FROM content
WHERE id = $1 AND user_id = $2
`

type GetContentByIDAndUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetContentByIDAndUser(ctx context.Context, arg GetContentByIDAndUserParams) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByIDAndUser, arg.ID, arg.UserID)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.ProjectID,
		&i.DeclaredMimeType,
		&i.EffectiveMimeType,
		&i.Bucket,
		&i.ObjectName,
		&i.GcsUri,
		&i.PublicUrl,
		&i.UploadStatus,
		&i.ObjectGeneration,
		&i.SizeBytes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentChildren = `-- name: ListContentChildren :many
SELECT id, user_id, parent_id, project_id, declared_mime_type, effective_mime_type, bucket, object_name, gcs_uri, public_url, upload_status, object_generation, size_bytes, completed_at, created_at, updated_at FROM content
WHERE parent_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListContentChildrenParams struct {
	ParentID     pgtype.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListContentChildren(ctx context.Context, arg ListContentChildrenParams) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentChildren, arg.ParentID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Content{}
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.ProjectID,
			&i.DeclaredMimeType,
			&i.EffectiveMimeType,
			&i.Bucket,
			&i.ObjectName,
			&i.GcsUri,
			&i.PublicUrl,
			&i.UploadStatus,
			&i.ObjectGeneration,
			&i.SizeBytes,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
