// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package contentsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Content struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	ParentID          pgtype.UUID
	ProjectID         pgtype.UUID
	DeclaredMimeType  string
	EffectiveMimeType *string
	Bucket            string
	ObjectName        string
	GcsUri            *string
	PublicUrl         *string
	UploadStatus      string
	ObjectGeneration  *int64
	SizeBytes         *int64
	CompletedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
