// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package contentsqlc

import (
	"context"
)

type Querier interface {
	CompleteContent(ctx context.Context, arg CompleteContentParams) (Content, error)
	CreateContent(ctx context.Context, arg CreateContentParams) (Content, error)
	GetContentByBucketAndName(ctx context.Context, arg GetContentByBucketAndNameParams) (Content, error)
	GetContentByIDAndUser(ctx context.Context, arg GetContentByIDAndUserParams) (Content, error)
	ListContentChildren(ctx context.Context, arg ListContentChildrenParams) ([]Content, error)
}

var _ Querier = (*Queries)(nil)
