// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authsqlc

import (
	"context"
)

type Querier interface {
	ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (RefreshToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	GetRefreshTokenByHash(ctx context.Context, arg GetRefreshTokenByHashParams) (RefreshToken, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error
}

var _ Querier = (*Queries)(nil)
