// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package authsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = $1
WHERE id = $2 AND revoked_at IS NULL
RETURNING id, user_id, token_hash, family_id, expires_at, revoked_at, created_at
`

type ConsumeRefreshTokenParams struct {
	RevokedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, arg.RevokedAt, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    family_id,
    expires_at,
    revoked_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NULL,
    $6
)
RETURNING id, user_id, token_hash, family_id, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	FamilyID  pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

type GetRefreshTokenByHashParams struct {
	TokenHash string
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, arg GetRefreshTokenByHashParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, arg.TokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = $1
WHERE id = $2
`

type RevokeRefreshTokenParams struct {
	RevokedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.RevokedAt, arg.ID)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = $1
WHERE family_id = $2 AND revoked_at IS NULL
`

type RevokeTokenFamilyParams struct {
	RevokedAt pgtype.Timestamptz
	FamilyID  pgtype.UUID
}

func (q *Queries) RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, arg.RevokedAt, arg.FamilyID)
	return err
}
