// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postssqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
	Title     string
	Content   string
	Published bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
