// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package postssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id,
    author_id,
    title,
    content,
    published,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, author_id, title, content, published, created_at, updated_at
`

type CreatePostParams struct {
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
	Title     string
	Content   string
	Published bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Published,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1 AND author_id = $2
`

type DeletePostParams struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.AuthorID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, title, content, published, created_at, updated_at
FROM posts
WHERE id = $1
`

type GetPostByIDParams struct {
	ID pgtype.UUID
}

func (q *Queries) GetPostByID(ctx context.Context, arg GetPostByIDParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPosts = `-- name: ListAllPosts :many
SELECT id, author_id, title, content, published, created_at, updated_at
FROM posts
ORDER BY created_at DESC
LIMIT $2
OFFSET $1
`

type ListAllPostsParams struct {
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListAllPosts(ctx context.Context, arg ListAllPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listAllPosts, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, author_id, title, content, published, created_at, updated_at
FROM posts
WHERE published = TRUE
ORDER BY created_at DESC
LIMIT $2
OFFSET $1
`

type ListPublishedPostsParams struct {
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    title = $1,
    content = $2,
    published = $3,
    updated_at = $4
WHERE id = $5 AND author_id = $6
RETURNING id, author_id, title, content, published, created_at, updated_at
`

type UpdatePostParams struct {
	Title     string
	Content   string
	Published bool
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Content,
		arg.Published,
		arg.UpdatedAt,
		arg.ID,
		arg.AuthorID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
