// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postssqlc

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeletePost(ctx context.Context, arg DeletePostParams) error
	GetPostByID(ctx context.Context, arg GetPostByIDParams) (Post, error)
	ListAllPosts(ctx context.Context, arg ListAllPostsParams) ([]Post, error)
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
